[pytest]
testpaths = tests/
pythonpath = .
addopts = --verbose --tracing retain-on-failure --screenshot only-on-failure --env local
markers =
    e2e: mark test as E2E
    api: mark test as API
    integ: mark test as integration
    bug: mark test as bug
    smoke: mark test as smoke
    reg: mark test as regression
    perf: mark test as performance
    sec: mark test as security